### ISSUE TITLE
[Wrong Icon] Showing Angular icon for TS files

### ISSUE THREAD

**Issue by nachocapodanno** [miguelsolorio/vscode-fluent-icons#30]
**Describe the bug**
For some files with this name: mock.service.ts, it shows an Angular icon.

**Expected behavior**
It should show TS icon as other file with this name: mock.ts

**Screenshots**
<img width="274" alt="Screenshot 2024-04-09 at 11 22 30" src="https://github.com/miguelsolorio/vscode-fluent-icons/assets/1399598/418b43d6-f967-4580-aef5-db6e8866fc98">

**Additional context**
Version Fluent v0.0.18

**Comment by miguelsolorio** [comment]
@nachocapodanno i think you meant to file this in https://github.com/miguelsolorio/vscode-symbols since this is for the Fluent product icon theme that doesn’t modify file icons?

**Comment by nachocapodanno** [comment]
yes @miguelsolorio sorry for my misunderstanding. Thanks!
