### ISSUE TITLE
Change GitHub Copilot Icon

### ISSUE THREAD

**Issue by JoaoGFdev** [miguelsolorio/vscode-fluent-icons#31]
In issue #21, there was a suggestion to replace the current icon with a generic robot icon.
However, I believe the existing **GitHub Copilot** icon aligns well with the theme and changing the logo of such an iconic product/feature might not be necessary.

Also there is other icons for the extension that's different from the one being used

Icon when Copilot is active
![image](https://github.com/miguelsolorio/vscode-fluent-icons/assets/42418197/82c1de2e-0621-4c47-a848-257ab26e2d53)
Icon when Copilot is disabled
![image](https://github.com/miguelsolorio/vscode-fluent-icons/assets/42418197/e1911a2e-78c3-44c1-bf6d-091148c5487d)

Icon for the Copilot chat
![image](https://github.com/miguelsolorio/vscode-fluent-icons/assets/42418197/9173ce3f-088b-4969-a7e8-c4050c46f108)

Additionally, updating the Chat icon in the **GitHub Copilot Chat** extension to better match the theme could be considered.

**Comment by raky291** [comment]
yes, I'm agree, is there a way to show the official icon?

**Comment by JoaoGFdev** [comment]
@miguelsolorio any thoughts on that?
